### ISSUE TITLE
doesnt seem to work, goCart undefined when using build files

### ISSUE THREAD

**Issue by drewlonious** [bornfight/goCart.js#10]
would love any sort of help on this!

**Comment by marioloncarek** [comment]
Hello, could you please provide some error codes or anything that could help us for debugging ?

**Comment by marioloncarek** [comment]
@drewlonious any new infos on this?

**Comment by patrickbolle** [comment]
Same issue here.

Trying to use the build files directly in Shopify theme and I receive this error when trying to init the library:
```
var goCart = new GoCart();
ReferenceError: GoCart is not defined
```

Let me know if I can provide any more details. Thanks for the library!

**Comment by tobiasger** [comment]
Same issue here.

**Comment by marioloncarek** [comment]
This issue is now fixed and docs are updated! 
@tobiasger @patrickbolle @drewlonious
