### ISSUE TITLE
Make currency sign a variable

### ISSUE THREAD

**Issue by christophberinger** [bornfight/goCart.js#11]
Cool plugin, thank you guys!

For the moment, the cart show prices with a dollar sign, even if the shops currency is different (euro). 

Would be super nice if you could provide an update here to just use the shops currency without adding a static dollar sign.

Thanks and cheers

**Comment by marioloncarek** [comment]
Yes, that can be done, thanks for input, will do it todat and let you know

**Comment by marioloncarek** [comment]
hey @christophberinger , i made a new option for currency! You can now update goCart to latest version and its done, and i also made changes to readme explaining how to use the option: 
[https://github.com/bornfight/goCart.js#moneybag-currency-options](https://github.com/bornfight/goCart.js#moneybag-currency-options)

Please let me know if everything is working, and is it simple enough for everyone?

**Comment by christophberinger** [comment]
Nice one @marioloncarek, works like a charm. Thanks bro! Closing this

**Comment by marioloncarek** [comment]
No problem, thanks for feedback!
