### ISSUE TITLE
Multiple cart triggers

### ISSUE THREAD

**Issue by jonXmack** [bornfight/goCart.js#16]
I'm working on a site which has two different layouts for the header for mobile/desktop so requires two cart icons. As it stands it's not possible to have more than one `js-go-cart-trigger` element due to the js using `querySelector`, so my mobile header doesn't trigger the cart overlay. 

Would it be possible for the js to be modified so `cartTrigger` uses `querySelectorAll` and a `forEach` in the same way the `cartModalClose` does instead? 

I'd be happy to submit a pull request myself if preferred. Thanks.

**Comment by marioloncarek** [comment]
@jonXmack please do provide an PR and i will make sure to check and merge it ASAP. Please tag me because i have some notification problems

**Comment by cfxd** [comment]
@jonXmack while I'm waiting (and praying 🙏🏻) for my PR to be merged, you can always create a little listener which will listen for a click on all the triggers and then trigger a click on the one that actually works 🤠

**Comment by jonXmack** [comment]
@cfxd I actually ended up moving `GoCart.js` into my project rather than importing from `node_modules` as I needed to make a bunch of other changes to it for but your PR is exactly what I did!

**Comment by marioloncarek** [comment]
@cfxd @jonXmack merged, thanks for your time from the whole team and sorry for waiting.
