### ISSUE TITLE
Cart drawer not triggering after adding to cart

### ISSUE THREAD

**Issue by anta199** [bornfight/goCart.js#17]
Hi, thanks for the great plugin!
I've implemented the cart and everything seems to work fine. I'm able to open the cart when clicking on the button and all the content is updating properly in the cart drawer.

The problem comes when I add a product to the cart from the product page – it purchases the item but redirects to the cart page, instead of opening the drawer like in the examples you offer.

I'm not getting any console error so I basically have no clue about what might be happening.
Is this a common problem? 

Thanks in advance

**Comment by marioloncarek** [comment]
@anta199 Please make sure u followed the instructions for changing the product form, this sounds like event is not preventing default behaviour, are you missing some css class used by JS?
