### ISSUE TITLE
Not mobile responsive

### ISSUE THREAD

**Issue by trev-dev** [bornfight/goCart.js#23]
I've tested the demo and my own deployment of this cart plugin and while things look OK while resizing the window in Chrome/Firefox, if you actually view it on a mobile browser or with FireFox's IOS presets, the sliding cart breaks out of the viewport and overflows.

![Screen Shot 2021-01-13 at 13 58 38](https://user-images.githubusercontent.com/28788713/104515375-943f2e00-55a7-11eb-9e3d-f78b0f2ce3a0.png)

On the previously mentioned deployment this is what we have:

![blurred](https://user-images.githubusercontent.com/28788713/104515830-2cd5ae00-55a8-11eb-9c3b-5563364f1da0.png)

**Comment by marioloncarek** [comment]
@trev-dev im checking on this link: https://ajax-cart-plugin-npm-test.myshopify.com/products/classic-leather-jacket and responsive seems ok, also we are using gocart on every project and never experienced this kind of behaviour, can you please check your implementation?

**Comment by trev-dev** [comment]
@marioloncarek The second screenshot I gave was definitely _way_ out of wack due to some transform breaking fixed positioning. It's brutal, but solved by killing the overflow on the html element.

The link you provided, however, does not work in Firefox's iOS emulation and on Firefox & Chrome on my Android device. It overflows and I have to scroll horizontally/vertically to find the buttons.

Making my own adjustments to the styles gets results for my project so it's a small issue.

**Comment by marioloncarek** [comment]
probably the best option is to take scss and just make adjustments for your project

**Comment by trev-dev** [comment]
Okay, but my remark here still stands and has nothing to do with me:

> The link you provided, however, does not work in Firefox's iOS emulation and on Firefox & Chrome on my Android device. It overflows and I have to scroll horizontally/vertically to find the buttons.

You should be able to replicate it.
