### ISSUE TITLE
Cart Item doesnt populate in Cart Drawer or Cart Modal

### ISSUE THREAD

**Issue by jazzu21** [bornfight/goCart.js#24]
as soon as the page load, there's a popup that says 'Something went wrong, please contact us!'

**Comment by jazzu21** [comment]
![image](https://user-images.githubusercontent.com/77476385/108128784-3f339200-70e8-11eb-80f0-8e8ccd143f3f.png)

![image](https://user-images.githubusercontent.com/77476385/108129019-8c176880-70e8-11eb-92e4-6b373b992e49.png)

this is the error I got,

**Comment by jazzu21** [comment]
I also made sure the body is loaded first before executing the JS, I'm not sure why I still get this error

**Comment by subgero** [comment]
Did you manage to solve this?

**Comment by jazzu21** [comment]
yes! i was able too.
