### ISSUE TITLE
Cart drawer not working properly on manual installation

### ISSUE THREAD

**Issue by ive93** [bornfight/goCart.js#25]
I followed all the steps and I keep getting this error, hope you can help me
![issue](https://user-images.githubusercontent.com/63221097/108674905-63161f80-74bc-11eb-89e7-e36e80307a13.png)

**Comment by subgero** [comment]
Did you manage to resolve this?

**Comment by stirtingale** [comment]
I am a bit late to the party @ive93 but I ran into this. The script checks the modal alongside the drawer. If you manually remove the modal then it fails. Either alter the js to remove references to the modal or leave the modal div in and it should resolve it
