### ISSUE TITLE
the cart drawer needs to be refreshed to see results

### ISSUE THREAD

**Issue by shazabb** [bornfight/goCart.js#26]
i could somehow created the functionality but facing an issue that i can not update the cart drawer when i add the product into the cart. I get that when i refresh the page and open the cart drawer. So basically it is not working the same as in the demo and I want that same functionality.
Please help me in this.
Thanks in advance.

**Comment by marioloncarek** [comment]
that means that something is breaking in the JS, please check your console it should tell you what the problem is
