### ISSUE TITLE
Moving items inside the cart

### ISSUE THREAD

**Issue by anta199** [bornfight/goCart.js#28]
Hello,
I'm trying to move the 'Remove' button position inside the cart.

I've managed to re-order some other items in the goCart.js file like the size but can't figure how to replace this button without messing up the rest of code.

Definitely what I'm asking is not an issue but I was wondering if there's a workaround on that?

Thanks

**Comment by marioloncarek** [comment]
you can do it with css, but also you can just take source from github and edit items in JS
