### ISSUE TITLE
Sometimes the cart drawer works and sometimes it just redirects to the cart page

### ISSUE THREAD

**Issue by jpjmortimer** [bornfight/goCart.js#29]
This happens on the same product.

I can click 'add to cart' on Product A and the cart drawer works as expected.

I then refresh and click 'add to cart' on Product A and I get redirected to the cart page instead, with the product added.

I then go back to the last page and click 'add to cart' on Product A and the cart drawer works as expected again.

Thanks!

**Comment by disruptivesocial2020** [comment]
Getting this same issue with the Debut theme.

**Comment by fatmarker** [comment]
@jpjmortimer Kicked myself. Thank you!
