### ISSUE TITLE
Disable scroll on background page

### ISSUE THREAD

**Issue by daviareias** [bornfight/goCart.js#40]
Just a small suggestion, it seems that when you open the cart, the background page is still scrollable, which may cause some confusion.

Adding "overflow: hidden;" to the body easily solve this.

**Comment by marioloncarek** [comment]
only adding overflow hidden will force page to scroll to top on open which is not good. feel free to use our lib which makes this feature working as expected: https://github.com/bornfight/b-scroll-lock .

**Comment by daviareias** [comment]
Thanks, I found that the scroll lock also expands by page for some reason, I added this and now looks ok:

this.body.style.maxWidth = '100%';
