### ISSUE TITLE
Improve development environment

### ISSUE THREAD

**Issue by renatoruk** [bornfight/goCart.js#5]
The current implementation relies on an active shopify store so that the api requests can work. We should you create tests that mock the api endpoints so the project can be developed in its encapsulation.

**Comment by Hamza-Mujahid** [comment]
Hi, I'm using GoCart.js for the first time I need some help on how to install it in my shopify theme. I'm stuck in step 5.

**Comment by marioloncarek** [comment]
Please create a new issue describing what issues you have so we can help you :)
