### ISSUE TITLE
Got two error in the console

### ISSUE THREAD

**Issue by KhalilAhmadDanish** [bornfight/goCart.js#50]
![image](https://user-images.githubusercontent.com/14087594/183101448-d815e939-0080-4418-a722-c1487146db9d.png)
I see this error on the console and these on the footer 
![image](https://user-images.githubusercontent.com/14087594/183101568-a10387f8-20c3-4f2d-bcd4-11ac16182257.png)
 
please help me to solve it

**Comment by KhalilAhmadDanish** [comment]
@nsorosac @cfxd @napravicukod @zzavrski Please save my day

**Comment by cfxd** [comment]
@ KhalilAhmadDanish impossible to help you without a URL, seeing the code, and steps to reproduce

**Comment by KhalilAhmadDanish** [comment]
I did all the steps from the guidance to add it to my Shopify theme but have those two errors on site here is the preview link on the stage theme https://truwild.com/products/hydrate?_ab=0&_fd=0&_sc=1 if you check the console you will those two errors and if you scroll down to the bottom of the page you will see the second screenshot error too.

**Comment by KhalilAhmadDanish** [comment]
![image](https://user-images.githubusercontent.com/14087594/183224477-95c97cd5-6d09-40b5-96cf-2b29f5cd57c7.png)
Js file included 
![image](https://user-images.githubusercontent.com/14087594/183224506-2c7785e2-9907-4b40-8bd1-a385185a45a1.png)
the CSS file included 
![image](https://user-images.githubusercontent.com/14087594/183224579-3dc79155-bc35-4002-9161-ee6ac67a0287.png)
Where I included the files in the theme.liquid file
and if you check I add the goCart class to the add to cart in the product page but I spent about 12 hrs and didn't get why it's not working.

**Comment by KhalilAhmadDanish** [comment]
Now I got two new errors after including the CSS file in the theme.liquid
![image](https://user-images.githubusercontent.com/14087594/183225482-62d467f8-1b3b-4414-afaa-0e4f81897db0.png)
 it's the first error when you refresh the page and when I click on the cart to show the current items with the gocart button i have added I see this error:
![image](https://user-images.githubusercontent.com/14087594/183225602-35f7dce7-e4dc-4257-b61c-bc4634b00919.png)

**Comment by KhalilAhmadDanish** [comment]
I got it thank you
