### ISSUE TITLE
Implementation on non-ES6 projects?

### ISSUE THREAD

**Issue by bmsimo** [bornfight/goCart.js#9]
I've been trying to implement goCart.js on a non-ES6 shopify theme with no good result.

Could you provide instructions on how to? none of the (production/development/test) builds work, either nothing happens (if i don't add "new GoCart()") or i get GoCart is undefined.

I even tried to put the same production JS files you have on the demo, but then i get errors. I'm lost.

**Comment by drewlonious** [comment]
I second this, doesn't seem to work.

**Comment by BornaSepic** [comment]
Ran into the same issue as @drewlonious and @bmsimo. I ended up converting this file https://github.com/bornfight/goCart.js/blob/master/src/lib/GoCart.js to ES5 and using it in my project. So far haven't found any problems. But I'm sure it would be a good idea to include an ES5 version, especially since it's based on Shopify.

**Comment by abmenzel** [comment]
I am having this issue as well, resulting in GoCart undefined.

**Comment by bmsimo** [comment]
Have you checked  build/index.js?

Otherwise, you should check Webpack and @babel, it's life changing. It might be challenging at first, but it sure make your life easier.

In the end i did everything manually, with Fetch + Shopify's API

**Comment by abmenzel** [comment]
@bmsimo yeah I tried using the index.js, but I am having a hard time getting it to work. I'm not sure if i'm missing something, in order to get it to work by following the instructions alone.

**Comment by bmsimo** [comment]
You're better using webpack, check courses or the official documentation <https://webpack.js.org/> and then check this repo <https://github.com/hayes0724/shopify-webpack-themekit>

make sure to check that the course if for webpack 4

**Comment by patrickbolle** [comment]
Same issue here; frustrating as the library looks so great! Will look into the webpack setup; would love to be able to just drop this into a Shopify theme with no extra config though...

**Comment by haiquangtran** [comment]
Same here, I have been trying to use this library with debut.theme on shopify but had troubles.

**Comment by marioloncarek** [comment]
This issue is now fixed and docs are updated! 
@bmsimo @drewlonious @BornaSepic @abmenzel @patrickbolle @haiquangtran
